#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, cpSync } from "node:fs";
import { get as httpGet } from "node:http";
import { get as httpsGet } from "node:https";
import { basename, dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const GENERATED_BASE_ENTRIES = [
  "index.ts",
  "meta",
  "provider.ts",
  "types",
  "utilities.ts",
];

const GENERATED_METADATA_ENTRIES = new Set([
  "LICENSE",
  "LICENSE.md",
  "README.md",
  "package.json",
  "tsconfig.json",
]);

const packageRoot = resolve(process.cwd());
const packageJsonPath = join(packageRoot, "package.json");
const configPath = join(packageRoot, "crd2pulumi.config.mjs");

if (!existsSync(packageJsonPath)) {
  throw new Error(`Expected package.json in ${packageRoot}`);
}

if (!existsSync(configPath)) {
  throw new Error(`Expected crd2pulumi.config.mjs in ${packageRoot}`);
}

const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
const configModule = await import(pathToFileURL(configPath).href);
const config = configModule.default ?? configModule.config;

if (!config || !Array.isArray(config.sources) || config.sources.length === 0) {
  throw new Error("crd2pulumi.config.mjs must export { sources: [...] }");
}

const crdsDir = join(packageRoot, config.crdsDir ?? "crds");
const generatedDir = join(packageRoot, config.generatedDir ?? ".generated-crds");

rmSync(crdsDir, { force: true, recursive: true });
mkdirSync(crdsDir, { recursive: true });

let writtenCrds = 0;

for (const source of config.sources) {
  const sourceName = source.name ?? basename(source.url ?? source.path ?? "source");
  const yaml = await readSource(source, packageRoot);
  const crdDocs = splitYamlDocuments(yaml).filter(isCustomResourceDefinition);

  if (crdDocs.length === 0) {
    throw new Error(`No CustomResourceDefinition documents found in ${sourceName}`);
  }

  for (let index = 0; index < crdDocs.length; index += 1) {
    const doc = crdDocs[index].trimEnd();
    const crdName = extractMetadataName(doc) ?? `${sourceName}-${index + 1}`;
    const fileName =
      source.fileName && crdDocs.length === 1
        ? source.fileName
        : `${sanitizeFileName(crdName)}.yaml`;
    const header = [
      "# Generated by crd2pulumi-package-tools.",
      source.url ? `# Source: ${source.url}` : undefined,
      source.version ? `# Version: ${source.version}` : undefined,
    ]
      .filter(Boolean)
      .join("\n");

    writeFileSync(join(crdsDir, fileName), `${header}\n${doc}\n`);
    writtenCrds += 1;
  }
}

const crdPaths = readdirSync(crdsDir)
  .filter((fileName) => fileName.endsWith(".yaml") || fileName.endsWith(".yml"))
  .sort()
  .map((fileName) => join(crdsDir, fileName));

if (crdPaths.length === 0 || crdPaths.length !== writtenCrds) {
  throw new Error(`Expected ${writtenCrds} CRD files, found ${crdPaths.length}`);
}

rmSync(generatedDir, { force: true, recursive: true });
mkdirSync(generatedDir, { recursive: true });

const result = spawnSync(
  "crd2pulumi",
  [
    "--nodejsName",
    packageJson.name,
    "--nodejsPath",
    generatedDir,
    "--version",
    packageJson.version,
    ...crdPaths,
    "--force",
  ],
  { stdio: "inherit" },
);

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const generatedEntries = readdirSync(generatedDir).filter(
  (entry) => !GENERATED_METADATA_ENTRIES.has(entry),
);

for (const entry of new Set([
  ...GENERATED_BASE_ENTRIES,
  ...(config.cleanEntries ?? []),
  ...generatedEntries,
])) {
  const target = join(packageRoot, entry);
  if (existsSync(target)) {
    rmSync(target, { force: true, recursive: true });
  }
}

for (const entry of generatedEntries) {
  const source = join(generatedDir, entry);
  const target = join(packageRoot, entry);
  cpSync(source, target, { force: true, recursive: true });
}

patchGeneratedFiles(packageRoot, packageJson.name);

rmSync(generatedDir, { force: true, recursive: true });

console.log(
  `Generated ${packageJson.name} from ${crdPaths.length} CRDs in ${relativeSummary(packageRoot, crdsDir)}`,
);

async function readSource(source, root) {
  if (source.url) {
    return download(source.url);
  }

  if (source.path) {
    return readFileSync(resolve(root, source.path), "utf8");
  }

  throw new Error("CRD source must include either url or path");
}

async function download(url, redirectsRemaining = 5) {
  return new Promise((resolveDownload, reject) => {
    const parsedUrl = new URL(url);
    const get = parsedUrl.protocol === "http:" ? httpGet : httpsGet;

    get(parsedUrl, (response) => {
      const statusCode = response.statusCode ?? 0;
      const location = response.headers.location;

      if (statusCode >= 300 && statusCode < 400 && location) {
        response.resume();
        if (redirectsRemaining <= 0) {
          reject(new Error(`Too many redirects while downloading ${url}`));
          return;
        }
        const redirectedUrl = new URL(location, parsedUrl).toString();
        download(redirectedUrl, redirectsRemaining - 1).then(resolveDownload, reject);
        return;
      }

      if (statusCode < 200 || statusCode >= 300) {
        response.resume();
        reject(new Error(`Failed to download ${url}: HTTP ${statusCode}`));
        return;
      }

      response.setEncoding("utf8");
      let data = "";
      response.on("data", (chunk) => {
        data += chunk;
      });
      response.on("end", () => resolveDownload(data));
    }).on("error", reject);
  });
}

function splitYamlDocuments(yaml) {
  const docs = [];
  let current = [];

  for (const line of yaml.split(/\r?\n/)) {
    if (/^---\s*$/.test(line)) {
      const doc = current.join("\n").trim();
      if (doc.length > 0) {
        docs.push(doc);
      }
      current = [];
    } else {
      current.push(line);
    }
  }

  const finalDoc = current.join("\n").trim();
  if (finalDoc.length > 0) {
    docs.push(finalDoc);
  }

  return docs;
}

function isCustomResourceDefinition(doc) {
  return /^kind:\s*CustomResourceDefinition\s*$/m.test(doc);
}

function extractMetadataName(doc) {
  let inMetadata = false;

  for (const line of doc.split(/\r?\n/)) {
    if (!inMetadata) {
      inMetadata = line === "metadata:";
      continue;
    }

    if (/^\S/.test(line)) {
      return undefined;
    }

    const nameMatch = line.match(/^\s+name:\s*["']?([^"'\s]+)["']?\s*$/);
    if (nameMatch) {
      return nameMatch[1];
    }
  }

  return undefined;
}

function sanitizeFileName(name) {
  const sanitized = name.toLowerCase().replace(/[^a-z0-9_.-]+/g, "-");
  if (sanitized.length > 0) {
    return sanitized;
  }

  return createHash("sha256").update(name).digest("hex").slice(0, 16);
}

function patchGeneratedFiles(root, packageName) {
  const indexPath = join(root, "index.ts");
  if (existsSync(indexPath)) {
    const indexSource = readFileSync(indexPath, "utf8").replaceAll(
      "pulumi:providers:crds",
      `pulumi:providers:${packageName}`,
    );
    writeFileSync(indexPath, indexSource);
  }
}

function relativeSummary(root, path) {
  const stats = statSync(path);
  if (!stats.isDirectory()) {
    return path;
  }

  return path.startsWith(root) ? path.slice(root.length + 1) : dirname(path);
}
