#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { get as httpGet } from "node:http";
import { get as httpsGet } from "node:https";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const GENERATED_BASE_ENTRIES = [
  "index.ts",
  "meta",
  "provider.ts",
  "types",
  "utilities.ts",
];

const GENERATED_METADATA_ENTRIES = new Set([
  ".gitattributes",
  ".gitignore",
  "LICENSE",
  "LICENSE.md",
  "README.md",
  "package.json",
  "scripts",
  "tsconfig.json",
]);

if (isDirectRun()) {
  await main();
}

export async function main(root = process.cwd()) {
  const packageRoot = resolve(root);
  const packageJsonPath = join(packageRoot, "package.json");
  const configPath = join(packageRoot, "crd2pulumi.config.mjs");

  if (!existsSync(packageJsonPath)) {
    throw new Error(`Expected package.json in ${packageRoot}`);
  }

  if (!existsSync(configPath)) {
    throw new Error(`Expected crd2pulumi.config.mjs in ${packageRoot}`);
  }

  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
  const configModule = await import(pathToFileURL(configPath).href);
  const config = configModule.default ?? configModule.config;

  if (!config || !Array.isArray(config.sources) || config.sources.length === 0) {
    throw new Error("crd2pulumi.config.mjs must export { sources: [...] }");
  }

  const crdsDir = join(packageRoot, config.crdsDir ?? "crds");
  const generatedDir = join(packageRoot, config.generatedDir ?? ".generated-crds");

  rmSync(crdsDir, { force: true, recursive: true });
  mkdirSync(crdsDir, { recursive: true });

  let writtenCrds = 0;

  for (const source of config.sources) {
    const sourceName = source.name ?? basename(source.url ?? source.path ?? "source");
    const yaml = await readSource(source, packageRoot, config.downloadTimeoutMs);
    const crdDocs = splitYamlDocuments(yaml).filter(isCustomResourceDefinition);

    if (crdDocs.length === 0) {
      throw new Error(`No CustomResourceDefinition documents found in ${sourceName}`);
    }

    for (let index = 0; index < crdDocs.length; index += 1) {
      const doc = crdDocs[index].trimEnd();
      const crdName = extractMetadataName(doc) ?? `${sourceName}-${index + 1}`;
      const fileName =
        source.fileName && crdDocs.length === 1
          ? source.fileName
          : `${sanitizeFileName(crdName)}.yaml`;
      const header = [
        "# Generated by crd2pulumi-package-tools.",
        source.url ? `# Source: ${source.url}` : undefined,
        source.version ? `# Version: ${source.version}` : undefined,
      ]
        .filter(Boolean)
        .join("\n");

      writeFileSync(join(crdsDir, fileName), `${header}\n${doc}\n`);
      writtenCrds += 1;
    }
  }

  const crdPaths = readdirSync(crdsDir)
    .filter((fileName) => fileName.endsWith(".yaml") || fileName.endsWith(".yml"))
    .sort()
    .map((fileName) => join(crdsDir, fileName));

  if (crdPaths.length === 0 || crdPaths.length !== writtenCrds) {
    throw new Error(`Expected ${writtenCrds} CRD files, found ${crdPaths.length}`);
  }

  rmSync(generatedDir, { force: true, recursive: true });
  mkdirSync(generatedDir, { recursive: true });

  const result = spawnSync(
    "crd2pulumi",
    [
      "--nodejsName",
      packageJson.name,
      "--nodejsPath",
      generatedDir,
      "--version",
      packageJson.version,
      ...crdPaths,
      "--force",
    ],
    { stdio: "inherit" },
  );

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  const generatedEntries = readdirSync(generatedDir).filter(
    (entry) => !isGeneratedMetadataEntry(entry),
  );

  for (const entry of new Set([
    ...GENERATED_BASE_ENTRIES,
    ...(config.cleanEntries ?? []),
    ...generatedEntries,
  ])) {
    const target = join(packageRoot, entry);
    if (existsSync(target)) {
      rmSync(target, { force: true, recursive: true });
    }
  }

  for (const entry of generatedEntries) {
    const source = join(generatedDir, entry);
    const target = join(packageRoot, entry);
    cpSync(source, target, { force: true, recursive: true });
  }

  patchGeneratedFiles(packageRoot, packageJson.name, generatedEntries);

  rmSync(generatedDir, { force: true, recursive: true });

  console.log(
    `Generated ${packageJson.name} from ${crdPaths.length} CRDs in ${relativeSummary(packageRoot, crdsDir)}`,
  );
}

async function readSource(source, root, defaultTimeoutMs) {
  let contents;

  if (source.url) {
    contents = await download(
      source.url,
      source.timeoutMs ?? defaultTimeoutMs ?? 30000,
    );
  } else if (source.path) {
    contents = readFileSync(resolve(root, source.path), "utf8");
  } else {
    throw new Error("CRD source must include either url or path");
  }

  verifySourceSha256(source.name ?? source.url ?? source.path, contents, source.sha256);
  return contents;
}

async function download(url, timeoutMs = 30000, redirectsRemaining = 5) {
  return new Promise((resolveDownload, reject) => {
    const parsedUrl = new URL(url);
    const get = parsedUrl.protocol === "http:" ? httpGet : httpsGet;

    const request = get(parsedUrl, (response) => {
      const statusCode = response.statusCode ?? 0;
      const location = response.headers.location;

      if (statusCode >= 300 && statusCode < 400 && location) {
        response.resume();
        if (redirectsRemaining <= 0) {
          reject(new Error(`Too many redirects while downloading ${url}`));
          return;
        }
        const redirectedUrl = new URL(location, parsedUrl).toString();
        download(redirectedUrl, timeoutMs, redirectsRemaining - 1).then(
          resolveDownload,
          reject,
        );
        return;
      }

      if (statusCode < 200 || statusCode >= 300) {
        response.resume();
        reject(new Error(`Failed to download ${url}: HTTP ${statusCode}`));
        return;
      }

      response.setEncoding("utf8");
      let data = "";
      response.on("data", (chunk) => {
        data += chunk;
      });
      response.on("end", () => resolveDownload(data));
    }).on("error", reject);

    request.setTimeout(timeoutMs, () => {
      request.destroy(
        new Error(`Timed out downloading ${url} after ${timeoutMs}ms`),
      );
    });
  });
}

export function splitYamlDocuments(yaml) {
  const docs = [];
  let current = [];

  for (const line of yaml.split(/\r?\n/)) {
    if (/^---\s*$/.test(line)) {
      const doc = current.join("\n").trim();
      if (doc.length > 0) {
        docs.push(doc);
      }
      current = [];
    } else {
      current.push(line);
    }
  }

  const finalDoc = current.join("\n").trim();
  if (finalDoc.length > 0) {
    docs.push(finalDoc);
  }

  return docs;
}

export function isCustomResourceDefinition(doc) {
  return /^kind:\s*CustomResourceDefinition\s*$/m.test(doc);
}

export function extractMetadataName(doc) {
  let inMetadata = false;

  for (const line of doc.split(/\r?\n/)) {
    if (!inMetadata) {
      inMetadata = line === "metadata:";
      continue;
    }

    if (/^\S/.test(line)) {
      return undefined;
    }

    const nameMatch = line.match(/^\s+name:\s*["']?([^"'\s]+)["']?\s*$/);
    if (nameMatch) {
      return nameMatch[1];
    }
  }

  return undefined;
}

export function sanitizeFileName(name) {
  const sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (sanitized.length > 0) {
    return sanitized;
  }

  return createHash("sha256").update(name).digest("hex").slice(0, 16);
}

export function sha256Hex(source) {
  return createHash("sha256").update(source, "utf8").digest("hex");
}

export function verifySourceSha256(sourceName, contents, expectedSha256) {
  if (!expectedSha256) {
    return;
  }

  const actualSha256 = sha256Hex(contents);
  if (actualSha256 !== expectedSha256.toLowerCase()) {
    throw new Error(
      `SHA-256 mismatch for ${sourceName}: expected ${expectedSha256}, got ${actualSha256}`,
    );
  }
}

export function isGeneratedMetadataEntry(entry) {
  return GENERATED_METADATA_ENTRIES.has(entry);
}

export function patchGeneratedProviderTokens(source, packageName) {
  return source
    .replaceAll("pulumi:providers:crds", `pulumi:providers:${packageName}`)
    .replaceAll("pulumi:providers:kubernetes", `pulumi:providers:${packageName}`);
}

export function stripTrailingWhitespace(source) {
  return source.replace(/[ \t]+$/gm, "");
}

function patchGeneratedFiles(root, packageName, generatedEntries) {
  for (const entry of generatedEntries) {
    stripGeneratedTypeScript(join(root, entry));
  }

  const indexPath = join(root, "index.ts");
  if (existsSync(indexPath)) {
    writeFileSync(
      indexPath,
      patchGeneratedProviderTokens(readFileSync(indexPath, "utf8"), packageName),
    );
  }
}

function stripGeneratedTypeScript(path) {
  const stats = statSync(path);

  if (stats.isDirectory()) {
    for (const entry of readdirSync(path)) {
      stripGeneratedTypeScript(join(path, entry));
    }
    return;
  }

  if (!path.endsWith(".ts")) {
    return;
  }

  writeFileSync(path, stripTrailingWhitespace(readFileSync(path, "utf8")));
}

function isDirectRun() {
  return process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
}

function relativeSummary(root, path) {
  const stats = statSync(path);
  if (!stats.isDirectory()) {
    return path;
  }

  return path.startsWith(root) ? path.slice(root.length + 1) : dirname(path);
}
